#!/bin/sh
if [ -f /tmp/skin.xml ]; then
mv /tmp/skin.xml /usr/share/enigma2/XionLight
fi
echo "                                                          "
echo "             ...Skin successful installed.                "
echo "                                                          "
