#!/bin/sh
echo "Checking for previous installations..."
if [ -f /usr/share/enigma2/XionLight/skin.xml ]; then
    cp /usr/share/enigma2/XionLight/skin.xml /tmp
    rm -rf /usr/share/enigma2/XionLight
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MediaPortal/skins_720/XionLight
		echo "                                                           "
		echo "             Previous XionLight installation               "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/XionLight/plugin.py ]; then
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/XionLight
		echo "                                                           "
		echo "             XionLight configuration plugin                "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi




echo "                                                           "
echo "       The Skin XionLight is now being installed...        "
echo "                                                           "



