#!/bin/sh
echo "                                                           "
echo "       The Skin XionLight is now being removed...          "
echo "                                                           "
